#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Volumes/Second Partition 9/DevelopmentTools/gwt/gwt-mac-1.5.3/gwt-user.jar:/Volumes/Second Partition 9/DevelopmentTools/gwt/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.weborient.codemirror.CodemirrorGwt/CodemirrorGwt.html;
